version: "3.8"

services:
  admin-frontend:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: frontend-admin
    ports:
      - "3000:3000"
    environment:
      - SERVER_URL=http://localhost:8080
      # - SERVER_URL=http://192.168.1.137:8080


  customer-frontend:
    build:
      context: ./customer
      dockerfile: Dockerfile
    container_name: frontend-customer
    ports:
      - "4000:4000"
    environment:
      - SERVER_URL=http://localhost:8080
      # - SERVER_URL=http://192.168.1.137:8080


